// Existing rich saint records from the original All The Catholic Saints project.
const LOCAL_SAINTS = [// --- A ---
      {
        name: "Aaron of Aleth",
        birth: "unknown",
        death: "after 552",
        canonized: "",
        nationality: "Breton / French",
        type: "Hermit",
        century: "6th",
        knownFor: "Hermit and abbot in Brittany",
        intercession: "For a deeper life of prayer and solitude with God",
        notes: "Hermit"
      },
      {
        name: "Abbo of Fleury",
        birth: "945",
        death: "13 November 1004",
        canonized: "",
        nationality: "French",
        type: "Abbot / Scholar",
        century: "10th–11th",
        knownFor: "Scholar, abbot of Fleury, assisted Archbishop Oswald",
        intercession: "For scholars, teachers, and those seeking wisdom",
        notes: "Assisted Archbishop of Oswald"
      },
      {
        name: "Adalbert of Prague",
        birth: "956",
        death: "23 April 997",
        canonized: "3 February 999 by Pope Sylvester II",
        nationality: "Czech / Bohemian",
        type: "Bishop / Martyr",
        century: "10th",
        knownFor: "Bishop of Prague, missionary to the Prussians, martyr",
        intercession: "For missionaries and the conversion of peoples",
        notes: "His skull is preserved in St. Vitus Cathedral"
      },
      {
        name: "Adelaide of Italy",
        birth: "931",
        death: "16 December 999",
        canonized: "1097 by Pope Urban II",
        nationality: "Italian / Burgundian",
        type: "Empress / Widow",
        century: "10th",
        knownFor: "Holy Roman Empress, queen of Italy and Burgundy, known for charity and piety",
        intercession: "For widows, rulers, and those in positions of authority seeking to rule justly",
        notes: "Married layperson, empress"
      },
      {
        name: "Agnes of Rome",
        birth: "unknown",
        death: "304",
        canonized: "found in Roman Martyrology",
        nationality: "Roman / Italian",
        type: "Virgin / Martyr",
        century: "4th",
        knownFor: "Young virgin martyr who refused marriage and remained faithful to Christ",
        intercession: "For purity, young women, and those facing persecution for the faith",
        notes: "Virgin, martyr"
      },
      {
        name: "Aidan of Lindisfarne",
        birth: "c. 590",
        death: "31 August 651",
        canonized: "",
        nationality: "Irish",
        type: "Bishop / Missionary",
        century: "7th",
        knownFor: "Apostle of Northumbria, founded the monastery of Lindisfarne",
        intercession: "For missionaries, teachers, and the people of northern England",
        notes: ""
      },
      {
        name: "Albertus Magnus",
        birth: "before 1200",
        death: "15 November 1280",
        canonized: "16 December 1931 by Pope Pius XI",
        nationality: "German",
        type: "Bishop / Doctor of the Church",
        century: "13th",
        knownFor: "Doctor of the Church, philosopher, scientist, teacher of St. Thomas Aquinas",
        intercession: "For scientists, philosophers, students, and those seeking harmony between faith and reason",
        notes: "Doctor of the Church"
      },
      {
        name: "Aloysius Gonzaga",
        birth: "9 March 1568",
        death: "21 June 1591",
        canonized: "31 December 1726 by Pope Benedict XIII",
        nationality: "Italian",
        type: "Religious / Confessor",
        century: "16th",
        knownFor: "Jesuit novice known for purity and care of the plague-stricken",
        intercession: "For young people, purity, and those suffering from plague or contagious disease",
        notes: ""
      },
      {
        name: "Alphonsus Liguori",
        birth: "27 September 1696",
        death: "1 August 1787",
        canonized: "26 May 1839 by Pope Gregory XVI",
        nationality: "Italian",
        type: "Bishop / Doctor of the Church",
        century: "18th",
        knownFor: "Founder of the Redemptorists, Doctor of the Church, moral theologian",
        intercession: "For confessors, moral theologians, and those struggling with scruples",
        notes: "Doctor of the Church"
      },
      {
        name: "Ambrose of Milan",
        birth: "c. 340",
        death: "4 April 397",
        canonized: "found in Roman Martyrology",
        nationality: "Roman / Italian",
        type: "Bishop / Doctor of the Church",
        century: "4th",
        knownFor: "Bishop of Milan, Doctor of the Church, baptized St. Augustine",
        intercession: "For bishops, teachers of the faith, and those seeking conversion",
        notes: ""
      },
      {
        name: "Andrew the Apostle",
        birth: "c. 5 BC",
        death: "62 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "First-called of the Apostles, brother of St. Peter, preached in Greece and Scotland",
        intercession: "For fishermen, Scotland, Russia, and those called to follow Christ",
        notes: ""
      },
      {
        name: "Angela Merici",
        birth: "21 March 1474",
        death: "27 January 1540",
        canonized: "24 May 1807 by Pope Pius VII",
        nationality: "Italian",
        type: "Virgin / Foundress",
        century: "15th–16th",
        knownFor: "Foundress of the Ursulines, pioneer of women’s education",
        intercession: "For educators, young women, and those who care for the education of girls",
        notes: ""
      },
      {
        name: "Anthony of Padua",
        birth: "15 August 1195",
        death: "13 June 1231",
        canonized: "30 May 1232 by Pope Gregory IX",
        nationality: "Portuguese",
        type: "Priest / Doctor of the Church",
        century: "13th",
        knownFor: "Franciscan preacher, Doctor of the Church, finder of lost things",
        intercession: "For the recovery of lost items, the poor, and those seeking to preach the Gospel",
        notes: "Doctor of the Church"
      },
      {
        name: "Anthony the Great",
        birth: "12 January 251",
        death: "17 January 356",
        canonized: "found in Roman Martyrology",
        nationality: "Egyptian",
        type: "Hermit / Abbot",
        century: "3rd–4th",
        knownFor: "Father of monasticism, hermit in the Egyptian desert",
        intercession: "For monks, hermits, and those struggling against temptation",
        notes: ""
      },
      {
        name: "Augustine of Hippo",
        birth: "13 November 354",
        death: "28 August 430",
        canonized: "found in Roman Martyrology",
        nationality: "North African (Roman)",
        type: "Bishop / Doctor of the Church",
        century: "4th–5th",
        knownFor: "Doctor of the Church, author of Confessions and City of God, converted after a restless youth",
        intercession: "For conversion of sinners, theologians, and those seeking truth",
        notes: ""
      },
      {
        name: "Augustine of Canterbury",
        birth: "500s",
        death: "26 May 604",
        canonized: "found in Roman Martyrology",
        nationality: "Italian / Roman",
        type: "Bishop / Missionary",
        century: "6th–7th",
        knownFor: "First Archbishop of Canterbury, Apostle of the English",
        intercession: "For England and the conversion of peoples",
        notes: "Founder of the English Church"
      },

      // --- B ---
      {
        name: "Barbara",
        birth: "200s",
        death: "200s–300s",
        canonized: "found in Roman Martyrology",
        nationality: "Unknown (traditionally Asia Minor)",
        type: "Virgin / Martyr",
        century: "3rd–4th",
        knownFor: "Virgin martyr, invoked against sudden death and storms",
        intercession: "Against lightning, fire, sudden death, and for miners and artillerymen",
        notes: ""
      },
      {
        name: "Barnabas",
        birth: "unknown",
        death: "61 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Cypriot / Jewish",
        type: "Apostle",
        century: "1st",
        knownFor: "Companion of St. Paul, early missionary, ‘son of encouragement’",
        intercession: "For encouragement, missionaries, and peacemakers",
        notes: ""
      },
      {
        name: "Bartholomew the Apostle",
        birth: "0s",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "One of the Twelve Apostles, traditionally martyred by flaying",
        intercession: "For those suffering skin diseases and for Armenia",
        notes: ""
      },
      {
        name: "Basil of Caesarea",
        birth: "329 or 330",
        death: "1 or 2 January 379",
        canonized: "found in Roman Martyrology",
        nationality: "Cappadocian / Greek",
        type: "Bishop / Doctor of the Church",
        century: "4th",
        knownFor: "Doctor of the Church, Father of Eastern monasticism, defender of the Trinity",
        intercession: "For monks, theologians, and those defending orthodoxy",
        notes: ""
      },
      {
        name: "Bede the Venerable",
        birth: "c. 673",
        death: "26 May 735",
        canonized: "found in Roman Martyrology",
        nationality: "English",
        type: "Priest / Doctor of the Church",
        century: "7th–8th",
        knownFor: "Doctor of the Church, historian of the English Church, scholar and monk",
        intercession: "For historians, scholars, and writers",
        notes: "Also known as the Venerable Bede"
      },
      {
        name: "Benedict of Nursia",
        birth: "2 March 480",
        death: "21 March 547",
        canonized: "1220 by Pope Honorius III",
        nationality: "Italian",
        type: "Abbot / Founder",
        century: "5th–6th",
        knownFor: "Father of Western monasticism, author of the Rule of St. Benedict",
        intercession: "For Europe, monks, against poison, and for a balanced life of prayer and work",
        notes: ""
      },
      {
        name: "Bernadette Soubirous",
        birth: "7 January 1844",
        death: "16 April 1879",
        canonized: "8 December 1933 by Pope Pius XI",
        nationality: "French",
        type: "Virgin / Visionary",
        century: "19th",
        knownFor: "Visionary of Our Lady of Lourdes, humble and obedient",
        intercession: "For the sick, the poor, and those who feel insignificant",
        notes: ""
      },
      {
        name: "Bernard of Clairvaux",
        birth: "1090",
        death: "20 August 1153",
        canonized: "18 January 1174 by Pope Alexander III",
        nationality: "French",
        type: "Abbot / Doctor of the Church",
        century: "12th",
        knownFor: "Doctor of the Church, reformer of the Cistercians, preacher of the Second Crusade",
        intercession: "For contemplatives, against spiritual dryness, and for the Church",
        notes: "Reformer of the Cistercian Order"
      },
      {
        name: "Blaise",
        birth: "200s",
        death: "316",
        canonized: "found in Roman Martyrology",
        nationality: "Armenian",
        type: "Bishop / Martyr",
        century: "4th",
        knownFor: "Bishop and martyr, famous for the blessing of throats",
        intercession: "For throat ailments and protection of the voice",
        notes: ""
      },
      {
        name: "Bonaventure",
        birth: "1221",
        death: "15 July 1274",
        canonized: "14 April 1482 by Pope Sixtus IV",
        nationality: "Italian",
        type: "Bishop / Doctor of the Church",
        century: "13th",
        knownFor: "Doctor of the Church, Franciscan theologian and minister general",
        intercession: "For theologians and those seeking mystical union with God",
        notes: ""
      },
      {
        name: "Boniface",
        birth: "c. 675",
        death: "5 June 754",
        canonized: "",
        nationality: "English",
        type: "Bishop / Martyr",
        century: "8th",
        knownFor: "Apostle of Germany, martyred while preaching",
        intercession: "For Germany and missionaries",
        notes: ""
      },
      {
        name: "Bridget of Sweden",
        birth: "c. 1303",
        death: "23 July 1373",
        canonized: "7 October 1391 by Pope Boniface IX",
        nationality: "Swedish",
        type: "Widow / Foundress",
        century: "14th",
        knownFor: "Mystic, foundress of the Bridgettines, mother of St. Catherine of Sweden",
        intercession: "For widows, large families, and those seeking deeper prayer",
        notes: ""
      },
      {
        name: "Brigid of Kildare",
        birth: "c. 451",
        death: "c. 525",
        canonized: "found in Roman Martyrology",
        nationality: "Irish",
        type: "Abbess / Virgin",
        century: "5th–6th",
        knownFor: "One of the patron saints of Ireland, foundress of Kildare",
        intercession: "For Ireland, dairy workers, and those in need of hospitality",
        notes: ""
      },

      // --- C ---
      {
        name: "Catherine of Siena",
        birth: "25 March 1347",
        death: "29 April 1380",
        canonized: "29 April 1461 by Pope Pius II",
        nationality: "Italian",
        type: "Virgin / Doctor of the Church",
        century: "14th",
        knownFor: "Doctor of the Church, mystic, advisor to popes, instrumental in returning the papacy to Rome",
        intercession: "For Italy, nurses, and those seeking to influence the Church through prayer and counsel",
        notes: ""
      },
      {
        name: "Catherine of Alexandria",
        birth: "c. 287",
        death: "c. 305",
        canonized: "found in Roman Martyrology",
        nationality: "Egyptian / Alexandrian",
        type: "Virgin / Martyr",
        century: "4th",
        knownFor: "Scholarly virgin martyr, patroness of philosophers and students",
        intercession: "For students, philosophers, librarians, and those facing intellectual challenges to the faith",
        notes: ""
      },
      {
        name: "Cecilia",
        birth: "100s",
        death: "222–235",
        canonized: "found in Roman Martyrology",
        nationality: "Roman / Italian",
        type: "Virgin / Martyr",
        century: "2nd–3rd",
        knownFor: "Patron saint of music and musicians",
        intercession: "For musicians, singers, and the beauty of sacred music",
        notes: ""
      },
      {
        name: "Charles Borromeo",
        birth: "2 October 1538",
        death: "3 November 1584",
        canonized: "1 November 1610 by Pope Paul V",
        nationality: "Italian",
        type: "Bishop / Confessor",
        century: "16th",
        knownFor: "Archbishop of Milan, leading figure of the Counter-Reformation, cared for plague victims",
        intercession: "For bishops, catechists, and those working in times of epidemic",
        notes: ""
      },
      {
        name: "Charles Lwanga",
        birth: "1 January 1860",
        death: "3 June 1886",
        canonized: "18 October 1964 by Pope Paul VI",
        nationality: "Ugandan",
        type: "Martyr",
        century: "19th",
        knownFor: "Leader of the Uganda Martyrs, burned alive for refusing the king’s immoral demands",
        intercession: "For African youth, purity, and those persecuted for the faith in Africa",
        notes: "One of the Uganda Martyrs"
      },
      {
        name: "Christopher",
        birth: "unknown",
        death: "c. 251",
        canonized: "found in Roman Martyrology",
        nationality: "Unknown (traditionally Canaanite or Lycian)",
        type: "Martyr",
        century: "3rd",
        knownFor: "Legendary carrier of the Christ Child, patron of travelers",
        intercession: "For safe travel and motorists",
        notes: ""
      },
      {
        name: "Clare of Assisi",
        birth: "16 July 1194",
        death: "11 August 1253",
        canonized: "26 September 1255 by Pope Alexander IV",
        nationality: "Italian",
        type: "Virgin / Foundress",
        century: "12th–13th",
        knownFor: "Foundress of the Poor Clares, close collaborator of St. Francis",
        intercession: "For television, eye diseases, and those living a life of evangelical poverty",
        notes: ""
      },
      {
        name: "Clement of Rome",
        birth: "c. 35 AD",
        death: "99 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Roman",
        type: "Pope / Martyr",
        century: "1st",
        knownFor: "Early pope, author of the First Letter of Clement",
        intercession: "For the Church of Rome and those seeking unity",
        notes: ""
      },
      {
        name: "Columba (Columban)",
        birth: "540",
        death: "23 November 615",
        canonized: "",
        nationality: "Irish",
        type: "Abbot / Missionary",
        century: "6th–7th",
        knownFor: "Irish missionary to the continent, founded Luxeuil and Bobbio",
        intercession: "For missionaries and the peoples of Europe",
        notes: ""
      },
      {
        name: "Cyprian of Carthage",
        birth: "c. 200",
        death: "14 September 258",
        canonized: "found in Roman Martyrology",
        nationality: "North African (Carthaginian)",
        type: "Bishop / Martyr",
        century: "3rd",
        knownFor: "Bishop of Carthage, theologian of the unity of the Church, martyr",
        intercession: "For bishops and the unity of the Church",
        notes: ""
      },
      {
        name: "Cyril and Methodius",
        birth: "826–827 / 815",
        death: "14 February 869 / 6 April 885",
        canonized: "found in Roman Martyrology",
        nationality: "Byzantine / Greek (worked among Slavs)",
        type: "Bishops / Apostles to the Slavs",
        century: "9th",
        knownFor: "Apostles to the Slavs, creators of the Glagolitic alphabet",
        intercession: "For the Slavic peoples and the unity of East and West",
        notes: ""
      },

      // --- D ---
      {
        name: "Damien of Molokai",
        birth: "3 January 1840",
        death: "15 April 1889",
        canonized: "11 October 2009 by Pope Benedict XVI",
        nationality: "Belgian",
        type: "Priest / Missionary",
        century: "19th",
        knownFor: "Missionary to the lepers of Molokai, died of leprosy himself",
        intercession: "For those with leprosy or other stigmatizing illnesses, and for caregivers",
        notes: "Known for his work with people with leprosy"
      },
      {
        name: "David of Wales",
        birth: "c. 500",
        death: "1 March 589",
        canonized: "",
        nationality: "Welsh",
        type: "Bishop / Confessor",
        century: "6th",
        knownFor: "Patron saint of Wales, monastic founder",
        intercession: "For Wales and those living a simple, austere life",
        notes: ""
      },
      {
        name: "Dominic de Guzmán",
        birth: "8 August 1170",
        death: "6 August 1221",
        canonized: "13 July 1234 by Pope Gregory IX",
        nationality: "Spanish",
        type: "Priest / Founder",
        century: "12th–13th",
        knownFor: "Founder of the Order of Preachers (Dominicans)",
        intercession: "For preachers, the Dominican Order, and those combating heresy through truth and charity",
        notes: ""
      },
      {
        name: "Dominic Savio",
        birth: "2 April 1842",
        death: "9 March 1857",
        canonized: "12 June 1954 by Pope Pius XII",
        nationality: "Italian",
        type: "Confessor",
        century: "19th",
        knownFor: "Student of St. John Bosco, model of youthful holiness",
        intercession: "For young people and students",
        notes: ""
      },

      // --- E ---
      {
        name: "Edith Stein (Teresa Benedicta of the Cross)",
        birth: "12 October 1891",
        death: "9 August 1942",
        canonized: "11 October 1998 by Pope John Paul II",
        nationality: "German (Jewish origin)",
        type: "Martyr / Philosopher",
        century: "20th",
        knownFor: "Jewish convert, Carmelite nun, philosopher, murdered at Auschwitz",
        intercession: "For Europe, Jewish converts, and those seeking truth through philosophy",
        notes: "Also known as Teresa Benedicta of the Cross"
      },
      {
        name: "Elizabeth Ann Seton",
        birth: "28 August 1774",
        death: "4 January 1821",
        canonized: "14 September 1975 by Pope Paul VI",
        nationality: "American",
        type: "Widow / Foundress",
        century: "18th–19th",
        knownFor: "First native-born American saint, foundress of the Sisters of Charity",
        intercession: "For widows, teachers, and the Catholic schools of America",
        notes: "First citizen born in the U.S. to be declared a saint"
      },
      {
        name: "Elizabeth of Hungary",
        birth: "7 July 1207",
        death: "17 November 1231",
        canonized: "27 May 1235 by Pope Gregory IX",
        nationality: "Hungarian",
        type: "Widow / Tertiary",
        century: "13th",
        knownFor: "Princess known for radical charity to the poor, associated with the miracle of the roses",
        intercession: "For the poor, the homeless, bakers, and those who care for the sick",
        notes: "Patron saint of the homeless"
      },
      {
        name: "Ephrem the Syrian",
        birth: "c. 306",
        death: "9 June 373",
        canonized: "found in Roman Martyrology",
        nationality: "Syrian",
        type: "Deacon / Doctor of the Church",
        century: "4th",
        knownFor: "Doctor of the Church, poet and hymnographer of the East",
        intercession: "For poets, hymn writers, and the churches of the Middle East",
        notes: ""
      },

      // --- F ---
      {
        name: "Faustina Kowalska",
        birth: "25 August 1905",
        death: "5 October 1938",
        canonized: "30 April 2000 by Pope John Paul II",
        nationality: "Polish",
        type: "Religious / Mystic",
        century: "20th",
        knownFor: "Apostle of Divine Mercy, received the revelations of the Divine Mercy image and chaplet",
        intercession: "For trust in God’s mercy and for sinners",
        notes: ""
      },
      {
        name: "Francis of Assisi",
        birth: "1181 or 1182",
        death: "3 October 1226",
        canonized: "16 July 1228 by Pope Gregory IX",
        nationality: "Italian",
        type: "Founder / Confessor",
        century: "12th–13th",
        knownFor: "Founder of the Franciscans, stigmatic, lover of poverty and creation",
        intercession: "For animals, the environment, the poor, and peace",
        notes: "Italian Roman Catholic friar and preacher"
      },
      {
        name: "Francis de Sales",
        birth: "21 August 1567",
        death: "28 December 1622",
        canonized: "8 April 1665 by Pope Alexander VII",
        nationality: "French / Savoyard",
        type: "Bishop / Doctor of the Church",
        century: "16th–17th",
        knownFor: "Doctor of the Church, gentle guide of souls, co-founder of the Visitation Order",
        intercession: "For writers, journalists, and those seeking a gentle path of holiness",
        notes: ""
      },
      {
        name: "Francis Xavier",
        birth: "7 April 1506",
        death: "2 December 1552",
        canonized: "12 March 1622 by Pope Gregory XV",
        nationality: "Spanish (Navarre)",
        type: "Priest / Missionary",
        century: "16th",
        knownFor: "Jesuit missionary to India, Japan, and the East Indies",
        intercession: "For missionaries and the peoples of Asia",
        notes: ""
      },
      {
        name: "Frances Xavier Cabrini",
        birth: "15 July 1850",
        death: "22 December 1917",
        canonized: "7 July 1946 by Pope Pius XII",
        nationality: "Italian (naturalized American)",
        type: "Virgin / Foundress",
        century: "19th–20th",
        knownFor: "First U.S. citizen to be canonized, foundress of the Missionary Sisters of the Sacred Heart",
        intercession: "For immigrants and hospital administrators",
        notes: "First U.S. citizen to be canonized"
      },

      // --- G ---
      {
        name: "George",
        birth: "200s",
        death: "23 April 303",
        canonized: "found in Roman Martyrology",
        nationality: "Cappadocian / Palestinian",
        type: "Martyr",
        century: "4th",
        knownFor: "Legendary dragon-slayer, soldier-martyr, patron of England and many other places",
        intercession: "For England, soldiers, and those facing seemingly impossible battles",
        notes: ""
      },
      {
        name: "Gerard Majella",
        birth: "6 April 1726",
        death: "16 October 1755",
        canonized: "11 December 1904 by Pope Pius X",
        nationality: "Italian",
        type: "Religious / Confessor",
        century: "18th",
        knownFor: "Redemptorist lay brother, known for miracles and care of mothers",
        intercession: "For expectant mothers, childbirth, and children",
        notes: ""
      },
      {
        name: "Gregory the Great",
        birth: "c. 540",
        death: "12 March 604",
        canonized: "found in Roman Martyrology",
        nationality: "Roman / Italian",
        type: "Pope / Doctor of the Church",
        century: "6th–7th",
        knownFor: "Pope, Doctor of the Church, sent Augustine to England, reformed the liturgy",
        intercession: "For popes, teachers, and those suffering from gout",
        notes: "Also called Gregory the Great"
      },
      {
        name: "Gregory of Nazianzus",
        birth: "329",
        death: "25 January 390",
        canonized: "found in Roman Martyrology",
        nationality: "Cappadocian / Greek",
        type: "Bishop / Doctor of the Church",
        century: "4th",
        knownFor: "Doctor of the Church, ‘The Theologian’, defender of the Trinity",
        intercession: "For theologians and those defending the divinity of Christ",
        notes: ""
      },

      // --- H ---
      {
        name: "Helena of Constantinople",
        birth: "c. 246 or 248",
        death: "c. 330",
        canonized: "found in Roman Martyrology",
        nationality: "Roman (mother of Constantine)",
        type: "Empress / Widow",
        century: "3rd–4th",
        knownFor: "Mother of Constantine, finder of the True Cross",
        intercession: "For archaeologists, converts, and difficult marriages",
        notes: ""
      },
      {
        name: "Hildegard of Bingen",
        birth: "1098",
        death: "17 September 1179",
        canonized: "10 May 2012 by Pope Benedict XVI",
        nationality: "German",
        type: "Abbess / Doctor of the Church",
        century: "12th",
        knownFor: "Doctor of the Church, mystic, composer, naturalist, and visionary",
        intercession: "For musicians, scientists, and those seeking the integration of faith and knowledge",
        notes: "Doctor of the Church"
      },
      {
        name: "Hippolytus of Rome",
        birth: "c. 170",
        death: "c. 235",
        canonized: "found in Roman Martyrology",
        nationality: "Roman",
        type: "Priest / Martyr",
        century: "2nd–3rd",
        knownFor: "Early Christian writer, antipope who later reconciled, martyr",
        intercession: "For those seeking reconciliation with the Church",
        notes: ""
      },

      // --- I ---
      {
        name: "Ignatius of Antioch",
        birth: "c. 50 AD",
        death: "c. 108 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Syrian / Antiochene",
        type: "Bishop / Martyr",
        century: "1st–2nd",
        knownFor: "Apostolic Father, wrote letters on the way to martyrdom in Rome",
        intercession: "For the unity of the Church and those facing martyrdom",
        notes: ""
      },
      {
        name: "Ignatius of Loyola",
        birth: "c. 23 October 1491",
        death: "31 July 1556",
        canonized: "12 March 1622 by Pope Gregory XV",
        nationality: "Spanish (Basque)",
        type: "Priest / Founder",
        century: "16th",
        knownFor: "Founder of the Society of Jesus (Jesuits), author of the Spiritual Exercises",
        intercession: "For retreats, spiritual directors, and the Society of Jesus",
        notes: "Founded the Society of Jesus"
      },
      {
        name: "Irenaeus of Lyons",
        birth: "c. 130",
        death: "c. 202",
        canonized: "found in Roman Martyrology",
        nationality: "Greek (Asia Minor) / worked in Gaul",
        type: "Bishop / Martyr",
        century: "2nd",
        knownFor: "Early Church Father, opponent of Gnosticism, author of Against Heresies",
        intercession: "For those defending orthodoxy against modern errors",
        notes: ""
      },
      {
        name: "Isidore of Seville",
        birth: "c. 556",
        death: "4 April 636",
        canonized: "found in Roman Martyrology",
        nationality: "Spanish",
        type: "Bishop / Doctor of the Church",
        century: "6th–7th",
        knownFor: "Doctor of the Church, last of the Western Church Fathers, encyclopedist",
        intercession: "For the internet, computer users, and students",
        notes: "Archbishop of Seville, Doctor of the Church"
      },
      {
        name: "Isidore the Laborer",
        birth: "c. 1070",
        death: "15 May 1130",
        canonized: "12 March 1622 by Pope Gregory XV",
        nationality: "Spanish",
        type: "Layman / Confessor",
        century: "11th–12th",
        knownFor: "Farmer saint, known for miracles and devotion while working the fields",
        intercession: "For farmers, rural communities, and those who work with their hands",
        notes: ""
      },

      // --- J ---
      {
        name: "James the Greater",
        birth: "c. 3 AD",
        death: "44 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "One of the Twelve, first apostle to be martyred, patron of Spain (Santiago)",
        intercession: "For Spain, pilgrims (especially on the Camino), and those seeking courage",
        notes: ""
      },
      {
        name: "Jane Frances de Chantal",
        birth: "28 January 1572",
        death: "13 December 1641",
        canonized: "16 July 1767 by Pope Clement XIII",
        nationality: "French",
        type: "Widow / Foundress",
        century: "16th–17th",
        knownFor: "Co-foundress of the Visitation Order with St. Francis de Sales",
        intercession: "For widows and those living a balanced life of prayer and action",
        notes: ""
      },
      {
        name: "Jerome",
        birth: "c. 347",
        death: "30 September 420",
        canonized: "found in Roman Martyrology",
        nationality: "Dalmatian / Roman",
        type: "Priest / Doctor of the Church",
        century: "4th–5th",
        knownFor: "Doctor of the Church, translator of the Vulgate Bible",
        intercession: "For Scripture scholars, translators, and librarians",
        notes: "Translated the Vulgate"
      },
      {
        name: "Joan of Arc",
        birth: "1412",
        death: "30 May 1431",
        canonized: "16 May 1920 by Pope Benedict XV",
        nationality: "French",
        type: "Virgin / Martyr",
        century: "15th",
        knownFor: "French heroine who led armies at the inspiration of heavenly voices, burned at the stake",
        intercession: "For France, soldiers, and those unjustly accused",
        notes: "French heroine and martyr"
      },
      {
        name: "John the Apostle",
        birth: "c. 6 AD",
        death: "c. 100 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Evangelist",
        century: "1st",
        knownFor: "Beloved disciple, author of the Fourth Gospel, three epistles, and Revelation",
        intercession: "For friendship with Christ, writers, and those seeking pure love",
        notes: ""
      },
      {
        name: "John the Baptist",
        birth: "1st century BC",
        death: "28–36 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish",
        type: "Prophet / Martyr",
        century: "1st",
        knownFor: "Forerunner of Christ, preacher of repentance, beheaded by Herod",
        intercession: "For conversion, baptismal grace, and those who prepare the way for others",
        notes: ""
      },
      {
        name: "John Bosco",
        birth: "16 August 1815",
        death: "31 January 1888",
        canonized: "1 April 1934 by Pope Pius XI",
        nationality: "Italian",
        type: "Priest / Founder",
        century: "19th",
        knownFor: "Founder of the Salesians, apostle of youth, educator of the poor",
        intercession: "For young people, educators, and those working with at-risk youth",
        notes: ""
      },
      {
        name: "John Chrysostom",
        birth: "c. 349",
        death: "14 September 407",
        canonized: "found in Roman Martyrology",
        nationality: "Syrian / Antiochene (worked in Constantinople)",
        type: "Bishop / Doctor of the Church",
        century: "4th–5th",
        knownFor: "Doctor of the Church, ‘Golden-mouthed’ preacher, Archbishop of Constantinople",
        intercession: "For preachers and those who suffer for speaking the truth",
        notes: ""
      },
      {
        name: "John of the Cross",
        birth: "1542",
        death: "14 December 1591",
        canonized: "27 December 1726 by Pope Benedict XIII",
        nationality: "Spanish",
        type: "Priest / Doctor of the Church",
        century: "16th",
        knownFor: "Doctor of the Church, mystic, reformer of Carmel with St. Teresa of Ávila",
        intercession: "For contemplatives, those in spiritual darkness, and poets",
        notes: ""
      },
      {
        name: "John Paul II",
        birth: "18 May 1920",
        death: "2 April 2005",
        canonized: "27 April 2014 by Pope Francis",
        nationality: "Polish",
        type: "Pope / Confessor",
        century: "20th–21st",
        knownFor: "Pope who helped end communism in Eastern Europe, apostle of Divine Mercy and the family",
        intercession: "For the family, young people, and the Church in times of cultural change",
        notes: ""
      },
      {
        name: "John Vianney",
        birth: "8 May 1786",
        death: "4 August 1859",
        canonized: "31 May 1925 by Pope Pius XI",
        nationality: "French",
        type: "Priest / Confessor",
        century: "19th",
        knownFor: "Curé of Ars, patron of parish priests, extraordinary confessor",
        intercession: "For parish priests and those seeking conversion through the sacrament of Confession",
        notes: ""
      },
      {
        name: "Joseph",
        birth: "1st century BC",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish",
        type: "Spouse of the Blessed Virgin / Confessor",
        century: "1st",
        knownFor: "Foster-father of Jesus, husband of Mary, patron of the Universal Church",
        intercession: "For fathers, workers, a happy death, and the protection of the Church",
        notes: "Husband of the Blessed Virgin Mary"
      },
      {
        name: "Josephine Bakhita",
        birth: "c. 1869",
        death: "8 February 1947",
        canonized: "1 October 2000 by Pope John Paul II",
        nationality: "Sudanese (lived in Italy)",
        type: "Religious / Confessor",
        century: "19th–20th",
        knownFor: "Former slave who became a Canossian sister, known for her radiant joy and forgiveness",
        intercession: "For victims of human trafficking and those who have suffered abuse",
        notes: ""
      },
      {
        name: "Jude the Apostle",
        birth: "0s",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "Apostle, patron of desperate and lost causes",
        intercession: "For impossible or desperate situations",
        notes: "Also known as Jude Thaddeus"
      },
      {
        name: "Justin Martyr",
        birth: "100",
        death: "165",
        canonized: "found in Roman Martyrology",
        nationality: "Palestinian / Roman",
        type: "Martyr / Apologist",
        century: "2nd",
        knownFor: "Early Christian apologist, philosopher who defended the faith before the emperor",
        intercession: "For philosophers and those defending the faith in public",
        notes: ""
      },

      // --- K ---
      {
        name: "Kateri Tekakwitha",
        birth: "1656",
        death: "17 April 1680",
        canonized: "21 October 2012 by Pope Benedict XVI",
        nationality: "Native American (Mohawk–Algonquin)",
        type: "Virgin / Confessor",
        century: "17th",
        knownFor: "First Native American saint, known for her purity and devotion despite opposition",
        intercession: "For Native Americans, ecology, and those who suffer for their faith within their own culture",
        notes: "First Native American to become a saint"
      },
      {
        name: "Katharine Drexel",
        birth: "26 November 1858",
        death: "3 March 1955",
        canonized: "1 October 2000 by Pope John Paul II",
        nationality: "American",
        type: "Virgin / Foundress",
        century: "19th–20th",
        knownFor: "Heiress who gave her fortune to serve Native Americans and African Americans",
        intercession: "For racial justice and those who serve marginalized communities",
        notes: ""
      },

      // --- L ---
      {
        name: "Lawrence of Rome",
        birth: "31 December 225",
        death: "10 August 258",
        canonized: "found in Roman Martyrology",
        nationality: "Spanish / Roman",
        type: "Deacon / Martyr",
        century: "3rd",
        knownFor: "Deacon of Rome, martyred on a gridiron, patron of the poor",
        intercession: "For the poor, deacons, and those who cook (humorously, for cooks)",
        notes: "Martyr of Rome"
      },
      {
        name: "Leo the Great",
        birth: "c. 400",
        death: "10 November 461",
        canonized: "found in Roman Martyrology",
        nationality: "Italian / Roman",
        type: "Pope / Doctor of the Church",
        century: "5th",
        knownFor: "Pope who met Attila the Hun, Doctor of the Church, defined the two natures of Christ",
        intercession: "For popes and those defending the true humanity and divinity of Christ",
        notes: "Also known as Leo the Great, Doctor of the Church"
      },
      {
        name: "Louis IX of France",
        birth: "25 April 1214",
        death: "25 August 1270",
        canonized: "11 July 1297 by Pope Boniface VIII",
        nationality: "French",
        type: "King / Confessor",
        century: "13th",
        knownFor: "Holy king of France, crusader, known for justice and piety",
        intercession: "For rulers, the French people, and those seeking to govern justly",
        notes: ""
      },
      {
        name: "Lucy of Syracuse",
        birth: "c. 283",
        death: "304",
        canonized: "found in Roman Martyrology",
        nationality: "Sicilian / Italian",
        type: "Virgin / Martyr",
        century: "4th",
        knownFor: "Virgin martyr, patroness of the blind and those with eye trouble",
        intercession: "For eye diseases and the blind",
        notes: ""
      },

      // --- M ---
      {
        name: "Margaret Mary Alacoque",
        birth: "22 July 1647",
        death: "17 October 1690",
        canonized: "13 May 1920 by Pope Benedict XV",
        nationality: "French",
        type: "Religious / Mystic",
        century: "17th",
        knownFor: "Apostle of the Sacred Heart of Jesus",
        intercession: "For devotion to the Sacred Heart and those seeking reparation",
        notes: ""
      },
      {
        name: "Maria Goretti",
        birth: "16 October 1890",
        death: "6 July 1902",
        canonized: "24 June 1950 by Pope Pius XII",
        nationality: "Italian",
        type: "Virgin / Martyr",
        century: "19th–20th",
        knownFor: "Young martyr of purity who forgave her attacker on her deathbed",
        intercession: "For purity, young people, and the grace of forgiveness",
        notes: ""
      },
      {
        name: "Mark the Evangelist",
        birth: "5 AD",
        death: "25 April 68",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish (associated with Alexandria and Rome)",
        type: "Evangelist / Martyr",
        century: "1st",
        knownFor: "Author of the second Gospel, companion of Peter and Paul",
        intercession: "For notaries, lawyers, and the city of Venice",
        notes: ""
      },
      {
        name: "Martha of Bethany",
        birth: "unknown",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish",
        type: "Disciple / Confessor",
        century: "1st",
        knownFor: "Sister of Mary and Lazarus, who served Jesus in her home",
        intercession: "For housewives, servants, and those who serve others in practical ways",
        notes: ""
      },
      {
        name: "Martin de Porres",
        birth: "9 December 1579",
        death: "3 November 1639",
        canonized: "6 May 1962 by Pope John XXIII",
        nationality: "Peruvian",
        type: "Religious / Confessor",
        century: "16th–17th",
        knownFor: "Dominican lay brother, known for charity, humility, and care of the sick and poor",
        intercession: "For racial harmony, social justice, and barbers",
        notes: ""
      },
      {
        name: "Martin of Tours",
        birth: "316 or 336",
        death: "8 November 397",
        canonized: "found in Roman Martyrology",
        nationality: "Hungarian-born / French",
        type: "Bishop / Confessor",
        century: "4th",
        knownFor: "Soldier who became a bishop, famous for sharing his cloak with a beggar",
        intercession: "For soldiers, the poor, and those discerning a new vocation",
        notes: ""
      },
      {
        name: "Mary, Mother of God",
        birth: "c. 8 September 18 BC",
        death: "0s (Assumption)",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish",
        type: "Mother of God / Queen of Saints",
        century: "1st",
        knownFor: "Mother of Jesus Christ, the Theotokos, assumed body and soul into heaven",
        intercession: "For all needs; she is the most powerful intercessor after Christ Himself",
        notes: "Mother of Jesus Christ"
      },
      {
        name: "Mary Magdalene",
        birth: "unknown",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish",
        type: "Disciple / Confessor",
        century: "1st",
        knownFor: "Apostle to the Apostles, first witness of the Resurrection",
        intercession: "For converts, those who have been forgiven much, and contemplatives",
        notes: ""
      },
      {
        name: "Matthew the Apostle",
        birth: "0s",
        death: "0s",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Evangelist",
        century: "1st",
        knownFor: "Tax collector called by Jesus, author of the first Gospel",
        intercession: "For accountants, bankers, and those seeking a new beginning",
        notes: ""
      },
      {
        name: "Maximilian Kolbe",
        birth: "8 January 1894",
        death: "14 August 1941",
        canonized: "10 October 1982 by Pope John Paul II",
        nationality: "Polish",
        type: "Priest / Martyr",
        century: "20th",
        knownFor: "Franciscan who volunteered to die in place of another prisoner at Auschwitz",
        intercession: "For prisoners, journalists, and those addicted to drugs or alcohol",
        notes: ""
      },
      {
        name: "Monica",
        birth: "332",
        death: "387",
        canonized: "found in Roman Martyrology",
        nationality: "North African (Berber / Roman)",
        type: "Widow / Confessor",
        century: "4th",
        knownFor: "Mother of St. Augustine, whose tears and prayers obtained his conversion",
        intercession: "For mothers, especially those praying for the conversion of their children",
        notes: ""
      },

      // --- N ---
      {
        name: "Nicholas of Myra",
        birth: "15 March 270",
        death: "6 December 342",
        canonized: "found in Roman Martyrology",
        nationality: "Asia Minor (Greek)",
        type: "Bishop / Confessor",
        century: "3rd–4th",
        knownFor: "Bishop known for secret generosity, origin of the Santa Claus tradition",
        intercession: "For children, sailors, and those in financial need",
        notes: ""
      },
      {
        name: "Nino (Nina) of Georgia",
        birth: "c. 280",
        death: "c. 332",
        canonized: "",
        nationality: "Cappadocian / Georgian",
        type: "Virgin / Equal-to-the-Apostles",
        century: "4th",
        knownFor: "Apostle of Georgia, brought Christianity to the Iberian kingdom",
        intercession: "For Georgia and those who evangelize through quiet witness",
        notes: ""
      },

      // --- O ---
      {
        name: "Óscar Romero",
        birth: "15 August 1917",
        death: "24 March 1980",
        canonized: "14 October 2018 by Pope Francis",
        nationality: "Salvadoran",
        type: "Bishop / Martyr",
        century: "20th",
        knownFor: "Archbishop of San Salvador, murdered while celebrating Mass for speaking against injustice",
        intercession: "For those who work for justice and peace, and for the Church in Latin America",
        notes: ""
      },

      // --- P ---
      {
        name: "Patrick of Ireland",
        birth: "unknown",
        death: "400s",
        canonized: "found in Roman Martyrology",
        nationality: "British (Roman Britain) / Irish by mission",
        type: "Bishop / Confessor",
        century: "5th",
        knownFor: "Apostle of Ireland, used the shamrock to explain the Trinity",
        intercession: "For Ireland and those seeking deliverance from spiritual bondage",
        notes: ""
      },
      {
        name: "Paul the Apostle",
        birth: "c. 5 AD",
        death: "c. 64 or 67 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish (Tarsus) / Roman citizen",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "Apostle to the Gentiles, author of many New Testament epistles",
        intercession: "For missionaries, converts, and those who struggle with their past",
        notes: ""
      },
      {
        name: "Paul VI",
        birth: "26 September 1897",
        death: "6 August 1978",
        canonized: "14 October 2018 by Pope Francis",
        nationality: "Italian",
        type: "Pope / Confessor",
        century: "20th",
        knownFor: "Pope of the Second Vatican Council’s implementation, author of Humanae Vitae",
        intercession: "For the Church in the modern world and for fidelity to the teaching on life",
        notes: ""
      },
      {
        name: "Peter the Apostle",
        birth: "c. 1 AD",
        death: "64–68 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Pope / Martyr",
        century: "1st",
        knownFor: "Prince of the Apostles, first Pope, crucified upside-down in Rome",
        intercession: "For the Pope, the Church of Rome, and those who have denied Christ and seek forgiveness",
        notes: ""
      },
      {
        name: "Philip Neri",
        birth: "21 July 1515",
        death: "25 May 1595",
        canonized: "12 March 1622 by Pope Gregory XV",
        nationality: "Italian",
        type: "Priest / Founder",
        century: "16th",
        knownFor: "Apostle of Rome, founder of the Oratory, known for joy and humor",
        intercession: "For joy, humor in the spiritual life, and the city of Rome",
        notes: ""
      },
      {
        name: "Pio of Pietrelcina (Padre Pio)",
        birth: "25 May 1887",
        death: "23 September 1968",
        canonized: "16 June 2002 by Pope John Paul II",
        nationality: "Italian",
        type: "Priest / Confessor",
        century: "19th–20th",
        knownFor: "Capuchin friar, stigmatic, extraordinary confessor and intercessor",
        intercession: "For the sick, for spiritual warfare, and for those seeking a deeper life of prayer",
        notes: ""
      },

      // --- R ---
      {
        name: "Rita of Cascia",
        birth: "c. 1381",
        death: "22 May 1457",
        canonized: "24 May 1900 by Pope Leo XIII",
        nationality: "Italian",
        type: "Widow / Religious",
        century: "14th–15th",
        knownFor: "Patroness of impossible causes, abused wife who became an Augustinian nun",
        intercession: "For impossible causes, difficult marriages, and those who have suffered abuse",
        notes: ""
      },
      {
        name: "Rose of Lima",
        birth: "20 April 1586",
        death: "24 August 1617",
        canonized: "12 April 1671 by Pope Clement X",
        nationality: "Peruvian",
        type: "Virgin / Tertiary",
        century: "16th–17th",
        knownFor: "First saint of the Americas, known for severe penances and love of the poor",
        intercession: "For the Americas, florists, and those seeking to live a life of hidden penance",
        notes: ""
      },

      // --- S ---
      {
        name: "Scholastica",
        birth: "c. 480",
        death: "10 February 543",
        canonized: "found in Roman Martyrology",
        nationality: "Italian",
        type: "Virgin / Abbess",
        century: "5th–6th",
        knownFor: "Twin sister of St. Benedict, foundress of a women’s community under the Rule",
        intercession: "For nuns and those who desire deeper conversation with God",
        notes: ""
      },
      {
        name: "Sebastian",
        birth: "c. 256",
        death: "c. 288",
        canonized: "found in Roman Martyrology",
        nationality: "Roman / Italian (possibly Gallic origin)",
        type: "Martyr",
        century: "3rd",
        knownFor: "Soldier-martyr shot with arrows, recovered, then beaten to death",
        intercession: "For athletes, soldiers, and those suffering from plague",
        notes: ""
      },
      {
        name: "Stephen the Protomartyr",
        birth: "5 AD",
        death: "34 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Jewish (Hellenist)",
        type: "Deacon / Martyr",
        century: "1st",
        knownFor: "First Christian martyr, whose death was witnessed by Saul (Paul)",
        intercession: "For deacons, stonemasons, and those who forgive their persecutors",
        notes: ""
      },

      // --- T ---
      {
        name: "Teresa of Ávila",
        birth: "28 March 1515",
        death: "4 October 1582",
        canonized: "12 March 1622 by Pope Gregory XV",
        nationality: "Spanish",
        type: "Virgin / Doctor of the Church",
        century: "16th",
        knownFor: "Doctor of the Church, reformer of Carmel, mystic and writer on prayer",
        intercession: "For those seeking a deeper life of prayer and for Spain",
        notes: ""
      },
      {
        name: "Teresa of Calcutta (Mother Teresa)",
        birth: "26 August 1910",
        death: "5 September 1997",
        canonized: "4 September 2016 by Pope Francis",
        nationality: "Albanian-born (Indian by citizenship)",
        type: "Virgin / Foundress",
        century: "20th",
        knownFor: "Foundress of the Missionaries of Charity, servant of the poorest of the poor",
        intercession: "For the poor, the dying, and those who feel unwanted",
        notes: ""
      },
      {
        name: "Thérèse of Lisieux",
        birth: "2 January 1873",
        death: "30 September 1897",
        canonized: "17 May 1925 by Pope Pius XI",
        nationality: "French",
        type: "Virgin / Doctor of the Church",
        century: "19th",
        knownFor: "Doctor of the Church, ‘Little Flower’, teacher of the Little Way of spiritual childhood",
        intercession: "For missionaries, florists, and those who feel small and ordinary",
        notes: ""
      },
      {
        name: "Thomas Aquinas",
        birth: "1225",
        death: "7 March 1274",
        canonized: "18 July 1323 by Pope John XXII",
        nationality: "Italian",
        type: "Priest / Doctor of the Church",
        century: "13th",
        knownFor: "Doctor of the Church, greatest of the Scholastic theologians, author of the Summa Theologiae",
        intercession: "For students, theologians, and those seeking clarity of mind",
        notes: ""
      },
      {
        name: "Thomas More",
        birth: "7 February 1478",
        death: "6 July 1535",
        canonized: "19 May 1935 by Pope Pius XI",
        nationality: "English",
        type: "Martyr / Layman",
        century: "15th–16th",
        knownFor: "Lord Chancellor of England, martyred for refusing to acknowledge Henry VIII as head of the Church",
        intercession: "For lawyers, politicians, and those facing difficult moral choices in public life",
        notes: ""
      },
      {
        name: "Thomas the Apostle",
        birth: "0s",
        death: "3 July 72 AD",
        canonized: "found in Roman Martyrology",
        nationality: "Galilean / Jewish",
        type: "Apostle / Martyr",
        century: "1st",
        knownFor: "‘Doubting Thomas’ who confessed ‘My Lord and my God’, missionary to India",
        intercession: "For those who struggle with doubt and for the Church in India",
        notes: ""
      },

      // --- V ---
      {
        name: "Vincent de Paul",
        birth: "24 April 1581",
        death: "27 September 1660",
        canonized: "16 June 1737 by Pope Clement XII",
        nationality: "French",
        type: "Priest / Founder",
        century: "16th–17th",
        knownFor: "Apostle of Charity, founder of the Vincentians and the Daughters of Charity",
        intercession: "For charitable organizations and those who serve the poor",
        notes: ""
      },
      {
        name: "Vincent Ferrer",
        birth: "23 January 1350",
        death: "5 April 1419",
        canonized: "3 June 1455 by Pope Callixtus III",
        nationality: "Spanish (Valencian)",
        type: "Priest / Confessor",
        century: "14th–15th",
        knownFor: "Dominican preacher who traveled Europe calling for conversion and the end of the Western Schism",
        intercession: "For builders, construction workers, and those seeking conversion",
        notes: ""
      },

      // --- W ---
      {
        name: "Wenceslaus",
        birth: "c. 911",
        death: "28 September 935",
        canonized: "found in Roman Martyrology",
        nationality: "Bohemian / Czech",
        type: "Duke / Martyr",
        century: "10th",
        knownFor: "Duke of Bohemia, murdered by his brother, patron of the Czech people",
        intercession: "For the Czech Republic and those who rule with justice",
        notes: ""
      }];

// Featured modern and especially relevant saints for this project.
LOCAL_SAINTS.push(
  {name:"Carlo Acutis",birth:"3 May 1991",death:"12 October 2006",feast:"12 October",canonized:"7 September 2025 by Pope Leo XIV",nationality:"Italian",type:"Layman / Computer enthusiast",century:"20th–21st",knownFor:"Italian Catholic teenager known for Eucharistic devotion and for using computers and the internet to share Catholic faith and catalog Eucharistic miracles.",intercession:"Young people, computer users, evangelization, and the internet",notes:"This website was deeply inspired by Saint Carlo Acutis, especially his life, his use of technology for evangelization, and his work creating a website about Eucharistic miracles.",image:"https://upload.wikimedia.org/wikipedia/en/c/c8/Carlo_Acutis_%28born_1991%29.jpg",website:"https://www.miracolieucaristici.org/"},
  {name:"Pier Giorgio Frassati",birth:"6 April 1901",death:"4 July 1925",feast:"4 July",canonized:"7 September 2025 by Pope Leo XIV",nationality:"Italian",type:"Layman",century:"20th",knownFor:"Young Italian Catholic known for charity, mountain climbing, friendship, and active service to the poor.",intercession:"Youth, students, mountaineers, and charitable works",notes:"Canonized with Saint Carlo Acutis in 2025."},
  {name:"Teresa of Calcutta",birth:"26 August 1910",death:"5 September 1997",feast:"5 September",canonized:"4 September 2016 by Pope Francis",nationality:"Albanian-Indian",type:"Religious / Founder",century:"20th",knownFor:"Founder of the Missionaries of Charity and a life devoted to serving the poor and abandoned.",intercession:"The poor, sick, homeless, and missionaries"},
  {name:"John Paul II",birth:"18 May 1920",death:"2 April 2005",feast:"22 October",canonized:"27 April 2014 by Pope Francis",nationality:"Polish",type:"Pope",century:"20th–21st",knownFor:"Pope of the Catholic Church from 1978 to 2005 and a major figure in modern Catholic evangelization.",intercession:"Families, youth, and the Church"},
  {name:"John Henry Newman",birth:"21 February 1801",death:"11 August 1890",feast:"9 October",canonized:"13 October 2019 by Pope Francis",nationality:"English",type:"Cardinal / Priest / Theologian",century:"19th",knownFor:"English theologian, convert, priest, cardinal, and founder of the Birmingham Oratory.",intercession:"Educators, theologians, and seekers of truth"},
  {name:"Maximilian Kolbe",birth:"8 January 1894",death:"14 August 1941",feast:"14 August",canonized:"10 October 1982 by Pope John Paul II",nationality:"Polish",type:"Priest / Martyr / Religious",century:"20th",knownFor:"Franciscan priest and martyr who served prisoners and founded Catholic publications and communities.",intercession:"Prisoners, journalists, families, and the pro-life movement"},
  {name:"Josemaría Escrivá",birth:"9 January 1902",death:"26 June 1975",feast:"26 June",canonized:"6 October 2002 by Pope John Paul II",nationality:"Spanish",type:"Priest / Founder",century:"20th",knownFor:"Founder of Opus Dei and preacher of the universal call to holiness in ordinary life.",intercession:"Lay people, workers, families, and priests"},
  {name:"Elizabeth Ann Seton",birth:"28 August 1774",death:"4 January 1821",feast:"4 January",canonized:"14 September 1975 by Pope Paul VI",nationality:"American",type:"Religious / Founder",century:"18th–19th",knownFor:"First native-born citizen of the United States to be canonized and founder of the American Sisters of Charity.",intercession:"Teachers, widows, converts, and Catholic schools"}
);
